/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NavigationMenu: typeof import('./src/components/NavigationMenu.vue')['default']
    NavigationMenuListItem: typeof import('./src/components/NavigationMenuListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
